packages:
  - examples/*
  - packages/*

onlyBuiltDependencies:
  - esbuild
  - unrs-resolver
catalog:
  vite: npm:@voidzero-dev/vite-plus-core@0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
  vitest: 4.1.11
  vite-plus: 0.0.0-commit.fba044cf40fea5a7bf4a2ee97822f174eab33dfa
overrides:
  vite@*: 'catalog:'
  vitest@*: 'catalog:'
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    react: '*'
    react-dom: '*'
    vite: '*'
    vitest: '*'
